export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'

export const FETCH_USER_INFO_REQUEST = 'FETCH_USER_INFO_REQUEST'
export const FETCH_USER_INFO_SUCCESS = 'FETCH_USER_INFO_SUCCESS'
export const FETCH_USER_INFO_FAILURE = 'FETCH_USER_INFO_FAILURE'

export const FETCH_USER_REPO_REQUEST = 'FETCH_USER_REPO_REQUEST'
export const FETCH_USER_REPO_SUCCESS = 'FETCH_USER_REPO_SUCCESS'
export const FETCH_USER_REPO_FAILURE = 'FETCH_USER_REPO_FAILURE'
